openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:443/api/v1
  description: Generated server url
paths:
  /tour/all:
    get:
      tags:
      - tour-controller
      summary: Get all tours
      operationId: getTours
      responses:
        "200":
          description: Found tours
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tour"
components:
  schemas:
    Tour:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
