// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/tourdetail": {
    params: {};
  };
  "/poidetail": {
    params: {};
  };
  "/route-builder": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/profile/friends": {
    params: {};
  };
  "/profile/tours": {
    params: {};
  };
  "/profile/groups": {
    params: {};
  };
  "/profile/notifications": {
    params: {};
  };
  "/login": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/signup" | "/tourdetail" | "/poidetail" | "/route-builder" | "/profile" | "/profile/friends" | "/profile/tours" | "/profile/groups" | "/profile/notifications" | "/login";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/" | "/signup" | "/tourdetail" | "/poidetail" | "/route-builder";
  };
  "routes/Index/Index.tsx": {
    id: "routes/Index/Index";
    page: "/";
  };
  "routes/Signup/Signup.tsx": {
    id: "routes/Signup/Signup";
    page: "/signup";
  };
  "routes/TourDetail/TourDetail.tsx": {
    id: "routes/TourDetail/TourDetail";
    page: "/tourdetail";
  };
  "routes/PointOfInterestDetail/PointOfInterestDetail.tsx": {
    id: "routes/PointOfInterestDetail/PointOfInterestDetail";
    page: "/poidetail";
  };
  "routes/RouteBuilder/RouteBuilder.tsx": {
    id: "routes/RouteBuilder/RouteBuilder";
    page: "/route-builder";
  };
  "layouts/ProfileLayout.tsx": {
    id: "layouts/ProfileLayout";
    page: "/profile" | "/profile/friends" | "/profile/tours" | "/profile/groups" | "/profile/notifications";
  };
  "routes/MyProfile/MyProfile.tsx": {
    id: "routes/MyProfile/MyProfile";
    page: "/profile";
  };
  "routes/MyFriends/MyFriends.tsx": {
    id: "routes/MyFriends/MyFriends";
    page: "/profile/friends";
  };
  "routes/MyTours/MyTours.tsx": {
    id: "routes/MyTours/MyTours";
    page: "/profile/tours";
  };
  "routes/MyGroups/MyGroups.tsx": {
    id: "routes/MyGroups/MyGroups";
    page: "/profile/groups";
  };
  "routes/MyNotifications/MyNotifications.tsx": {
    id: "routes/MyNotifications/MyNotifications";
    page: "/profile/notifications";
  };
  "routes/Login/Login.tsx": {
    id: "routes/Login/Login";
    page: "/login";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/home": typeof import("./src/routes/home.tsx");
  "routes/Index/Index": typeof import("./src/routes/Index/Index.tsx");
  "routes/Signup/Signup": typeof import("./src/routes/Signup/Signup.tsx");
  "routes/TourDetail/TourDetail": typeof import("./src/routes/TourDetail/TourDetail.tsx");
  "routes/PointOfInterestDetail/PointOfInterestDetail": typeof import("./src/routes/PointOfInterestDetail/PointOfInterestDetail.tsx");
  "routes/RouteBuilder/RouteBuilder": typeof import("./src/routes/RouteBuilder/RouteBuilder.tsx");
  "layouts/ProfileLayout": typeof import("./src/layouts/ProfileLayout.tsx");
  "routes/MyProfile/MyProfile": typeof import("./src/routes/MyProfile/MyProfile.tsx");
  "routes/MyFriends/MyFriends": typeof import("./src/routes/MyFriends/MyFriends.tsx");
  "routes/MyTours/MyTours": typeof import("./src/routes/MyTours/MyTours.tsx");
  "routes/MyGroups/MyGroups": typeof import("./src/routes/MyGroups/MyGroups.tsx");
  "routes/MyNotifications/MyNotifications": typeof import("./src/routes/MyNotifications/MyNotifications.tsx");
  "routes/Login/Login": typeof import("./src/routes/Login/Login.tsx");
};