// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/tourdetail": {
    params: {};
  };
  "/poidetail": {
    params: {};
  };
  "/unauthorized": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/profile/friends": {
    params: {};
  };
  "/profile/tours": {
    params: {};
  };
  "/profile/groups": {
    params: {};
  };
  "/profile/notifications": {
    params: {};
  };
  "/profile/payments": {
    params: {};
  };
  "/profile/edit": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/admin/poi": {
    params: {};
  };
  "/admin/billing": {
    params: {};
  };
  "/admin/profile": {
    params: {};
  };
  "/admin/notifications": {
    params: {};
  };
  "/admin/create": {
    params: {};
  };
  "/admin/addpoi": {
    params: {};
  };
  "/admin/tours": {
    params: {};
  };
  "/route-builder": {
    params: {};
  };
  "/login": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/signup" | "/tourdetail" | "/poidetail" | "/unauthorized" | "/profile" | "/profile/friends" | "/profile/tours" | "/profile/groups" | "/profile/notifications" | "/profile/payments" | "/profile/edit" | "/admin/users" | "/admin/poi" | "/admin/billing" | "/admin/profile" | "/admin/notifications" | "/admin/create" | "/admin/addpoi" | "/admin/tours" | "/route-builder" | "/login";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/" | "/signup" | "/tourdetail" | "/poidetail" | "/unauthorized";
  };
  "routes/index/index.tsx": {
    id: "routes/index/index";
    page: "/";
  };
  "routes/signup/signup.tsx": {
    id: "routes/signup/signup";
    page: "/signup";
  };
  "routes/tour-detail/tour-detail.tsx": {
    id: "routes/tour-detail/tour-detail";
    page: "/tourdetail";
  };
  "routes/point-of-interest-detail/point-of-interest-detail.tsx": {
    id: "routes/point-of-interest-detail/point-of-interest-detail";
    page: "/poidetail";
  };
  "routes/unauthorized/unauthorized.tsx": {
    id: "routes/unauthorized/unauthorized";
    page: "/unauthorized";
  };
  "layouts/profile-layout.tsx": {
    id: "layouts/profile-layout";
    page: "/profile" | "/profile/friends" | "/profile/tours" | "/profile/groups" | "/profile/notifications" | "/profile/payments" | "/profile/edit";
  };
  "routes/my-profile/my-profile.tsx": {
    id: "routes/my-profile/my-profile";
    page: "/profile";
  };
  "routes/my-profile/my-friends.tsx": {
    id: "routes/my-profile/my-friends";
    page: "/profile/friends";
  };
  "routes/my-profile/my-tours.tsx": {
    id: "routes/my-profile/my-tours";
    page: "/profile/tours";
  };
  "routes/my-profile/my-groups.tsx": {
    id: "routes/my-profile/my-groups";
    page: "/profile/groups";
  };
  "routes/my-profile/my-notifications.tsx": {
    id: "routes/my-profile/my-notifications";
    page: "/profile/notifications";
  };
  "routes/my-profile/my-payments.tsx": {
    id: "routes/my-profile/my-payments";
    page: "/profile/payments";
  };
  "routes/my-profile/edit-profile.tsx": {
    id: "routes/my-profile/edit-profile";
    page: "/profile/edit";
  };
  "layouts/admin-layout.tsx": {
    id: "layouts/admin-layout";
    page: "/admin/users" | "/admin/poi" | "/admin/billing" | "/admin/profile" | "/admin/notifications" | "/admin/create" | "/admin/addpoi" | "/admin/tours";
  };
  "routes/admin/user-management.tsx": {
    id: "routes/admin/user-management";
    page: "/admin/users";
  };
  "routes/admin/poi-management.tsx": {
    id: "routes/admin/poi-management";
    page: "/admin/poi";
  };
  "routes/admin/billing.tsx": {
    id: "routes/admin/billing";
    page: "/admin/billing";
  };
  "routes/admin/admin-profile.tsx": {
    id: "routes/admin/admin-profile";
    page: "/admin/profile";
  };
  "routes/admin/admin-notifications.tsx": {
    id: "routes/admin/admin-notifications";
    page: "/admin/notifications";
  };
  "routes/admin/create-admin-account.tsx": {
    id: "routes/admin/create-admin-account";
    page: "/admin/create";
  };
  "routes/admin/create-poi.tsx": {
    id: "routes/admin/create-poi";
    page: "/admin/addpoi";
  };
  "routes/admin/tour-management.tsx": {
    id: "routes/admin/tour-management";
    page: "/admin/tours";
  };
  "layouts/protected-layout.tsx": {
    id: "layouts/protected-layout";
    page: "/route-builder";
  };
  "routes/route-builder/route-builder.tsx": {
    id: "routes/route-builder/route-builder";
    page: "/route-builder";
  };
  "routes/login/login.tsx": {
    id: "routes/login/login";
    page: "/login";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/home": typeof import("./src/routes/home.tsx");
  "routes/index/index": typeof import("./src/routes/index/index.tsx");
  "routes/signup/signup": typeof import("./src/routes/signup/signup.tsx");
  "routes/tour-detail/tour-detail": typeof import("./src/routes/tour-detail/tour-detail.tsx");
  "routes/point-of-interest-detail/point-of-interest-detail": typeof import("./src/routes/point-of-interest-detail/point-of-interest-detail.tsx");
  "routes/unauthorized/unauthorized": typeof import("./src/routes/unauthorized/unauthorized.tsx");
  "layouts/profile-layout": typeof import("./src/layouts/profile-layout.tsx");
  "routes/my-profile/my-profile": typeof import("./src/routes/my-profile/my-profile.tsx");
  "routes/my-profile/my-friends": typeof import("./src/routes/my-profile/my-friends.tsx");
  "routes/my-profile/my-tours": typeof import("./src/routes/my-profile/my-tours.tsx");
  "routes/my-profile/my-groups": typeof import("./src/routes/my-profile/my-groups.tsx");
  "routes/my-profile/my-notifications": typeof import("./src/routes/my-profile/my-notifications.tsx");
  "routes/my-profile/my-payments": typeof import("./src/routes/my-profile/my-payments.tsx");
  "routes/my-profile/edit-profile": typeof import("./src/routes/my-profile/edit-profile.tsx");
  "layouts/admin-layout": typeof import("./src/layouts/admin-layout.tsx");
  "routes/admin/user-management": typeof import("./src/routes/admin/user-management.tsx");
  "routes/admin/poi-management": typeof import("./src/routes/admin/poi-management.tsx");
  "routes/admin/billing": typeof import("./src/routes/admin/billing.tsx");
  "routes/admin/admin-profile": typeof import("./src/routes/admin/admin-profile.tsx");
  "routes/admin/admin-notifications": typeof import("./src/routes/admin/admin-notifications.tsx");
  "routes/admin/create-admin-account": typeof import("./src/routes/admin/create-admin-account.tsx");
  "routes/admin/create-poi": typeof import("./src/routes/admin/create-poi.tsx");
  "routes/admin/tour-management": typeof import("./src/routes/admin/tour-management.tsx");
  "layouts/protected-layout": typeof import("./src/layouts/protected-layout.tsx");
  "routes/route-builder/route-builder": typeof import("./src/routes/route-builder/route-builder.tsx");
  "routes/login/login": typeof import("./src/routes/login/login.tsx");
};