spring.application.name=optitour

server.port = 443
spring.output.ansi.enabled=always

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/optitour
spring.datasource.username=root
spring.datasource.password=tfgOptitour
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.hibernate.ddl-auto=update
spring.web.error.include-message=always