name: OptiTour Continuous Integration complete workflow

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install modules
        working-directory: ./frontend
        run: npm install
      
      #We need react project to be running in order to execute E2E client test. 
      #We can execute the react project in background, so the terminal it's not blocked and is possible to run Spring Boot project simultaneously.
      #(This is not neccesary for Docker because it runs automatically in the GitHub actions runner)

      - name: Run React project in background
        working-directory: ./frontend
        run: VITE_API_BASE_URL=http://localhost:8080/api/v1 npm run dev -- --host localhost --port 5173 &
      
      #Once we have the react project running in background, now we can execute backend tests.
      - name: Set up Java environment
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
      
      # We'll also need to run backend, TourServiceE2ETest can call the api.
      # To do that, it's necessary to run a mysql database:

      - name: Configure and run MySQL
        run: |
          sudo systemctl start mysql
          sudo mysql --protocol=socket -uroot -proot <<'SQL'
          CREATE DATABASE IF NOT EXISTS optitour;
          ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'tfgOptitour';
          SQL

      - name: Run backend
        working-directory: ./backend/optitour
        run: mvn spring-boot:run -Dspring-boot.run.arguments="--server.port=8080" &

      - name: Wait for backend startup
        run: sleep 10
      
      - name: Run backend
        working-directory: ./backend/optitour
        run: mvn clean test

  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      #Now, we need backend to be runnig so we can run integration tests: 
      - name: Set up Java environment
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
      
      - name: Configure and run MySQL
        run: |
          sudo systemctl start mysql
          sudo mysql --protocol=socket -uroot -proot <<'SQL'
          CREATE DATABASE IF NOT EXISTS optitour;
          ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'tfgOptitour';
          SQL
      
      - name: Run backend
        working-directory: ./backend/optitour
        run: mvn spring-boot:run -Dspring-boot.run.arguments="--server.port=8080" &

      - name: Wait for backend startup
        run: sleep 10

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install modules
        working-directory: ./frontend
        run: npm install

      - name: Build React project
        working-directory: ./frontend
        run: npm run build

      - name: Run tests
        working-directory: ./frontend
        run: VITE_API_BASE_URL=http://localhost:8080/api/v1 npm test